# Generated by Django 5.0.6 on 2024-06-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profesor_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='usuario',
        ),
        migrations.AddField(
            model_name='propuesta',
            name='patrocinio',
            field=models.BooleanField(default=False),
        ),
    ]
